module uplift 

! Tectonic uplift scenarios for the ice-cascade model. Includes several simple uplift scenarios, and
!! can be expanded to include particular scenarios needed for new applications.

! Module contains:
!! upliftUniform: uniform uplift over the entire grid, at the rate given by upliftRate
!! upliftBlock1: block uplift of a N-S oriented block from L/4 to 3L/4
!! upliftBlock2: block uplift of a N-S oriented block from L/6 to 5L/4
!! upliftTri1: N-S triangular uplift from L/4 to 3L/4 
!! upliftTri2:  N-S triangular uplift from L/4 to 3L/4 

! Version info (auto-generated by svn):
!! $LastChangedDate: 2014-05-05 12:37:39 -0400 (Mon, 05 May 2014) $
!! $LastChangedBy: kfm $
!! $LastChangedRevision: 87 $ 

use types, only: dp
implicit none
private
public upliftUniform, upliftBlock1, upliftBlock2, upliftTri1, upliftTri2

contains

! ==================================================================================================
! upliftUniform: uniform uplift over the entire grid, at the rate given by upliftRate
! ==================================================================================================
subroutine upliftUniform ( upliftRate, upliftRateGrid )

! Arguments: 
!! upliftRate (in) = constant uplift rate, m/yr
!! upliftRateGrid (out) = gridded uplift rate, m/yr

real (dp), intent(in) :: upliftRate
real (dp), intent(out) :: upliftRateGrid(:,:)

upliftRateGrid = upliftRate
	
return
end subroutine upliftUniform

! ==================================================================================================
! upliftBlock1: block uplift of a N-S oriented block from L/4 to 3L/4
! ==================================================================================================
subroutine upliftBlock1 ( upliftRate, upliftRateGrid )

! Arguments: 
!! upliftRate (in) = constant uplift rate for the block, m/yr
!! upliftRateGrid (out) = gridded uplift rate, m/yr

real (dp), intent(in) :: upliftRate
real (dp), intent(out) :: upliftRateGrid(:,:)

integer :: i0, i1, nx

nx = size(upliftRateGrid,1)
i0 = nx/4
i1 = 3*nx/4
upliftRateGrid = 0.
upliftRateGrid(i0:i1,:) = upliftRate

return

end subroutine upliftBlock1

! ==================================================================================================
! upliftBlock2: block uplift of a N-S oriented block from L/6 to 5L/4
! ==================================================================================================
subroutine upliftBlock2 ( upliftRate, upliftRateGrid )

! Arguments: 
!! upliftRate (in) = constant uplift rate for the block, m/yr
!! upliftRateGrid (out) = gridded uplift rate, m/yr

real(dp), intent(in) :: upliftRate
real(dp), intent(out) :: upliftRateGrid(:,:)

integer :: i0, i1, nx

nx = size(upliftRateGrid,1)
i0 = nx/6
i1 = 5*nx/6
upliftRateGrid = 0.
upliftRateGrid(i0:i1,:) = upliftRate

return
end subroutine upliftBlock2

! ==================================================================================================
! upliftTri1: N-S triangular uplift from L/4 to 3L/4 
! ==================================================================================================
subroutine upliftTri1 ( upliftRate, upliftRateGrid )

! Arguments: 
!! upliftRate (in) = maximum uplift rate, at the apex of the triangle, m/yr
!! upliftRateGrid (out) = gridded uplift rate, m/yr

real(dp), intent(in) :: upliftRate
real(dp), intent(out) :: upliftRateGrid(:,:)

integer :: i, i0, i1, i2, nx
	
nx = size(upliftRateGrid,1)
i0 = nx/4
i1 = nx/2
i2 = 3*nx/4
upliftRateGrid = 0.
do i = i0,i1
	upliftRateGrid(i,:) = upliftRate*float(i-i0)/float(i1-i0)
end do 
do i = i1,i2
	upliftRateGrid(i,:) = upliftRate*(1.-float(i-i1)/float(i2-i1))
end do 

return
end subroutine upliftTri1

! ==================================================================================================
! upliftTri2: N-S triangular uplift from L/4 to 3L/4 	
! ==================================================================================================
subroutine upliftTri2 ( upliftRate, upliftRateGrid )

! Arguments: 
!! upliftRate (in) = maximum uplift rate, at the apex of the triangle, m/yr
!! upliftRateGrid (out) = gridded uplift rate, m/yr

real(dp), intent(in) :: upliftRate
real(dp), intent(out) :: upliftRateGrid(:,:)

integer :: i, i0, i1, i2, nx
	
nx = size(upliftRateGrid,1)
i0 = nx/6
i1 = nx/2
i2 = 5*nx/6
upliftRateGrid = 0.
do i = i0,i1
	upliftRateGrid(i,:) = upliftRate*float(i-i0)/float(i1-i0)
end do 
do i = i1,i2
	upliftRateGrid(i,:) = upliftRate*(1.-float(i-i1)/float(i2-i1))
end do 

return
end subroutine upliftTri2
	
end module uplift
