module hillslope

! Hillslope erosion model, including only simple hillslope diffusion.

! Module contains:
!! hillslopeDiffusion: computes erosion rate due to hillslope diffusion

! Version info (auto-generated by svn):
!! $LastChangedDate: 2014-05-09 00:15:08 -0400 (Fri, 09 May 2014) $
!! $LastChangedBy: kfm $
!! $LastChangedRevision: 93 $ 

use types, only: dp
implicit none
private
public hillslopeDiffusion

contains

! ==================================================================================================
! hillslopeDiffusion: computes erosion rate due to hillslope diffusion
! ==================================================================================================
subroutine hillslopeDiffusion ( z, dx, dy, coeff, nbc, sbc, ebc, wbc, mask, erorate )

! Arguments:
!! z (in) = elevation array
!! dx, dy (in) = grid spacing for z
!! coeff (in) = hillslope diffusivity
!! nbc, sbc, ebc, wbc (in) = integer labels for the type of boundary condition, specifically
!!! (0) for zero slope boundaries, and (1) for cyclic boundaries.
!! mask (in) = only compute erosion rate where mask==.true.
!! erorate (in) = hillslope erosion rate
 
logical, intent(in) :: mask(:,:)
integer, intent(in) :: nbc, sbc, ebc, wbc
real(dp), intent(in) :: dx, dy, coeff
real(dp), intent(inout) :: z(:,:) 
real(dp), intent(out) :: erorate(:,:)

integer :: i, j, nx, ny
real (dp) :: dl2
real(dp), allocatable :: zz(:,:)

! Get grid size
nx = size(z,1)
ny = size(z,2)
dl2=dx**2+dy**2

! Apply the BCs
!! Note: the simple treatment at non-cyclic edges is not physically correct, but it is close enough 
!!! and applies to a small enough portion of the domain that I don't bother coding the proper 
!!! forward or backward differences
!! Copy the topography into a grid with an empty 1-pt edge pad
allocate(zz(0:nx+1,0:ny+1))
zz(1:nx,1:ny) = z
!! Non-cyclic boundaries
if (nbc==0) zz(:,ny+1) = zz(:,ny)
if (sbc==0) zz(:,0) = zz(:,1)
if (ebc==0) zz(nx+1,:) = zz(nx,:)
if (wbc==0) zz(0,:) = zz(1,:)
!! Cyclic boundaries
if (nbc==1) zz(:,ny+1) = zz(:,1)
if (sbc==1) zz(:,0) = zz(:,ny)
if (ebc==1) zz(nx+1,:) = zz(1,:)
if (wbc==1) zz(0,:) = zz(nx,:)
	
! Compute erosion rate
do j=2,ny-1
	do i=2,nx-1
		if (mask(i,j)==.true.) then
			erorate(i,j) = &
				-coeff*((z(i+1,j)+z(i-1,j)-2.*z(i,j))/dx**2+(z(i,j+1)+z(i,j-1)-2.*z(i,j))/dy**2)/2. &
				-coeff*((z(i+1,j+1)+z(i-1,j-1)-4.*z(i,j)+z(i+1,j-1)+z(i-1,j+1))/dl2)/2.
		else
			erorate(i,j) = 0.
		end if 
	enddo
enddo

return
end subroutine hillslopeDiffusion

end module hillslope
