program ice_cascade

! Numerical model of glacial, fluvial, and hillslope erosion using modified versions of the ICE and
!! CASCADE models described in Braun & Sambridge, 1997, Basin Research; Braun et al, 1999, Annals of 
!! Glaciology; Herman et al, 2008, JGR; and others. The models are implemented in separate modules
!! called by this main program.
! 
! "Hungarian" prefixes are used to indicate the inteded usage of the variable:
!! p -> input parameter
!! f -> full-resolution grid
!! l -> low-resolution grid, include a 1-point pad on all sides used for boundary conditions

! Version info (auto-generated by svn):
!! $LastChangedDate: 2014-05-10 22:44:34 -0400 (Sat, 10 May 2014) $
!! $LastChangedBy: kfm $
!! $LastChangedRevision: 100 $ 

use types, only: dp 
use grid_module, only: grid_type
use time_module, only: time_type
use topo_module, only: topo_type
use hill_module, only: hill_type
use io_module, only: readParam
implicit none

!character(len=150) :: pRunName, pTopoFile, pIceFile
!logical :: pDoGlac, pDoFluv, pDoHill, pDoUplift, pDoEros, pDoFlex, pDoTemp, pDoTrackIceVol, &
!	pDoAddNoise, pDoPrefilter
!logical, allocatable :: fIceFree(:,:), fLake(:,:)
!integer :: ierr, proc, pBenchmark, lNx, fNx, lNy, fNy, pWriteFreq, step, outputStep, count0, &
!	countRate, pGlacBcN, pGlacBcS, pGlacBcE, pGlacBcW, pFluvBcN, pFluvBcS, pFluvBcE, pFluvBcW, &
!	pNxPad, pNyPad, pHillBcN, pHillBcS, pHillBcE, pHillBcW
!integer, allocatable :: pWriteFlag(:), fCatchment(:,:)
!real(dp) :: lDx, fDx, lDy, fDy, pTimeEnd, pTimeStepIceMax, pTimeStepIceMin, pTimeStep, pB, pBs, pGamma, pQheatb, &
!	pHeatConduct, pTempSlMin, pTempSlMax, pTempPeriod, pTempLapse, pTempYrRng, pMeltFact, &
!	pPrecipRate, pRhoIce, pRhoWater, pRhoCrust, pRhoMantle, pYm, pNu, pTe, pGlacErosFact, &
!	pFluvErosFact, pHillD, pUpliftRate, pGlacErosRateCeil, pTFloor, pTempDiffuse, pTempBasalGrad, &
!	pC, pCs, dvolIceSrc, dvolIceSnk, dvolIce, time, timeStepIceMean, tempSl, pBaseLvl
!real(dp), allocatable :: fX(:,:), fY(:,:), fH(:,:), fHT(:,:), fTInit(:,:), fHInit(:,:), &
!	fSliding(:,:), fUpliftRate(:,:), fGlacErosRate(:,:), fhillErosRate(:,:), fFluvErosRate(:,:), &
!	fSlope(:,:), fSolnH(:,:), lX(:,:), lY(:,:), lT(:,:), lH(:,:), lHT(:,:), lTempS(:,:), &
!	lTempB(:,:), lTempM(:,:), lBalRate(:,:), lUDefm(:,:), lVDefm(:,:), lUSlid(:,:), lVSlid(:,:), &
!	lSliding(:,:), lConstrict(:,:), fQWater(:,:), fWater(:,:), fFlex(:,:)

! NEW
type(grid_type) :: fgrid
type(time_type) :: time
type(topo_type) :: ftopo
type(hill_type) :: fhill


! Read model parameters
call readParam(fgrid, time, ftopo, fhill)
	
!! Allocate arrays
!!! High-res
!allocate( fX(fNx,fNy), fY(fNx,fNy), fT(fNx,fNy), fH(fNx,fNy), fHT(fNx,fNy), fTInit(fNx,fNy), &
!	fHInit(fNx,fNy), fSliding(fNx,fNy), fUpliftRate(fNx,fNy), fGlacErosRate(fNx,fNy), &
!	fIceFree(fNx,fNy), fhillErosRate(fNx,fNy), fSlope(fNx,fNy), fFluvErosRate(fNx,fNy), &
!	fSolnH(fNx,fNy), fQWater(fNx,fNy), fWater(fNx,fNy), fLake(fNx,fNy), fCatchment(fNx,fNy), &
!	fFlex(fNx,fNy))
!!! Low-res
!allocate( lX(lNx,lNy), lY(lNx,lNy), lT(lNx,lNy), lH(lNx,lNy), lHT(lNx,lNy), lTempS(lNx,lNy), &
!	lTempB(lNx,lNy), lTempM(lNx,lNy), lBalRate(lNx,lNy), lUDefm(lNx,lNy), lVDefm(lNx,lNy), &
!	lUSlid(lNx,lNy), lVSlid(lNx,lNy), lSliding(lNx,lNy), lConstrict(lNx,lNy) )

!! Populate grids with initial values
!call initGrids( pTopoFile, pIceFile, pBenchmark, lT, fT, lH, fH, lDx, lDy, fDx, fDy, lX, &
!	fX, lY, fY, pDoAddNoise, pDoPrefilter, pUpliftRate, pB, pRhoIce )

! Initialize objects
call fgrid%init()
call time%init()
call ftopo%init(fgrid)
call fhill%init(fgrid)

!! Create output file
!	call createOutput ( pRunName, pTopoFile, pIceFile, lNx, fNx, lNy, fNy, lDx, fDx, lDy, fDy, &
!		pDoEros, pDoFlex, pDoTemp, pTimeEnd, pTimeStepIceMax, pTimeStepIceMin, pTimeStep, pB, pBs, &
!		pGamma, pQheatb, pHeatConduct, pTempSlMin, pTempSlMax, pTempPeriod, pTempLapse, &
!		pTempYrRng, pMeltFact, pPrecipRate, pRhoIce, pRhoWater, pRhoCrust, pRhoMantle, pYm, pNu, &
!		pTe, pGlacErosFact, pHillD, pUpliftRate, pGlacErosRateCeil, pTFloor, pGlacBcN, pGlacBcS, &
!		pGlacBcE, pGlacBcW, pDoGlac, pDoFluv, pDoHill, pDoUplift, pDoTrackIceVol, pDoAddNoise, &
!		pDoPrefilter, pFluvBcN, pFluvBcS, pFluvBcE, pFluvBcW, pFluvErosFact, pBaseLvl, pNxPad, &
!		pNyPad, pHillBcN, pHillBcS, pHillBcE, pHillBcW, pWriteFlag )
!
!! Write initial values to output
!	call writeConst (fUpliftRate, fH, pWriteFlag)
!	call writeStep ( 1, 0._dp, pWriteFlag, lH, fH, lT, fT, lHT, fHT, lTempS, lTempB, lTempM, &
!		lUDefm, lVDefm, lUSlid, lVSlid, lSliding, fSliding, lConstrict, fGlacErosRate, &
!		fhillErosRate, fSlope, fQWater, fFluvErosRate, fWater, dvolIceSrc, dvolIceSnk, dvolIce, &
!		lBalRate, fLake, fCatchment, 0._dp, 0._dp, fFlex, fH)
!
!! Setup main loop
!step = 0
!outputStep = 1
!time = 0.
!!! Setup clock
!call system_clock (count0, countRate) 
!

do while (time%now .lt. time%finish) ! main loop

	! Trim last time step if needed
	if ((time%now+time%step) .gt. time%finish) time%step = time%finish-time%now	
	
!
!  !! Hillslope model
!  if (fhill%on) call fhill%run(fT, pTimeStep)
!			
	! Step forward
	time%now = time%now+time%step
  time%now_step = time%now_step+1
	
	! Write output
  if (time%write_now()) then
    print *, "WRITE"
  end if
!	if (( step/pWriteFreq*pWriteFreq==step) .or. (time==pTimeEnd) )  then
!
!		outputStep = outputStep + 1			
!
!		call writeStep ( outputStep, time, pWriteFlag, lH, fH, lT, fT, lHT, fHT, lTempS, lTempB, &
!			lTempM, lUDefm, lVDefm, lUSlid, lVSlid, lSliding, fSliding, lConstrict, fGlacErosRate, &
!			fhillErosRate, fSlope, fQWater, fFluvErosRate, fWater, dvolIceSrc, dvolIceSnk, &
!			dvolIce, lBalRate, fLake, fCatchment, timeStepIceMean, tempSl, fFlex, fSolnH)
!	
!    end if
!		
end do ! exit main loop		

!! End program
!if (proc.eq.0) call closeOutput()

end program ice_cascade
