module types

! Common variable type definitions used by the ice-cascade model

! Version info (auto-generated by svn):
!! $LastChangedDate: 2014-05-05 12:37:39 -0400 (Mon, 05 May 2014) $
!! $LastChangedBy: kfm $
!! $LastChangedRevision: 87 $ 

use, intrinsic :: iso_fortran_env, only: real64, real32
use netcdf, only: nf90_float, nf90_double, nf90_int
use mpi, only: mpi_double_precision, mpi_real

implicit none

save
private :: dummy_dp, dummy_sp

integer, parameter :: dp = real64
integer, parameter :: sp = real32
integer, parameter :: dp_mpi = mpi_double_precision
integer, parameter :: sp_mpi = mpi_real
integer, parameter :: dp_nc = nf90_double
integer, parameter :: sp_nc = nf90_float
integer, parameter :: int_nc = nf90_int

real(dp) :: dummy_dp
real(sp) :: dummy_sp
real(dp), parameter :: dp_eps = epsilon(dummy_dp)
real(dp), parameter :: sp_eps = epsilon(dummy_sp)

end module types
